import type { RawEventInput, SocialSignal } from "./schemas.js";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const SAMPLE_RAW_EVENTS: RawEventInput[] = [
  {
    id: "evt-001",
    title: "TCMB politika faizini 250 baz puan indirdi",
    summary:
      "Merkez Bankası Para Politikası Kurulu, politika faizini yüzde 46,5'e çekti. Karar piyasalarda kur ve tahvil tarafında hareketlilik yarattı.",
    category: "finance",
    sourceNames: ["TCMB", "TRT Haber", "Reuters"],
    sourceTrustScore: 0.95,
    verificationState: "official",
    importanceScore: 0.92,
    verificationScore: 0.98,
    locationRelevance: 0.85,
    marketImpactScore: 0.95,
    socialVelocityScore: 0.7,
    noveltyScore: 0.95,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(0.5),
    tags: ["faiz", "tcmb", "piyasa"],
    isOfficialSource: true,
  },
  {
    id: "evt-002",
    title: "AFAD: Marmara'da 4.2 büyüklüğünde deprem",
    summary:
      "Kandilli ve AFAD verilerine göre deprem Tekirdağ açıklarında kaydedildi. Tsunami riski bulunmuyor, hasar tespiti sürüyor.",
    category: "disaster",
    sourceNames: ["AFAD", "Kandilli", "TRT Haber"],
    sourceTrustScore: 0.98,
    verificationState: "official",
    importanceScore: 0.88,
    verificationScore: 0.99,
    locationRelevance: 0.9,
    marketImpactScore: 0.2,
    socialVelocityScore: 0.85,
    noveltyScore: 0.9,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(1),
    locationLabel: "Marmara / ev konumu yakını",
    isOfficialSource: true,
  },
  {
    id: "evt-003",
    title: "NATO liderler zirvesinde Ukrayna destek paketi genişletildi",
    summary:
      "Zirve sonuç bildirgesinde uzun menzilli sistem desteği ve çok yıllı finansman taahhüdü vurgulandı.",
    category: "geopolitics",
    sourceNames: ["NATO", "Reuters", "BBC"],
    sourceTrustScore: 0.93,
    verificationState: "verified",
    importanceScore: 0.9,
    verificationScore: 0.92,
    locationRelevance: 0.3,
    marketImpactScore: 0.55,
    socialVelocityScore: 0.6,
    noveltyScore: 0.85,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(2),
    tags: ["nato", "ukrayna", "savaş"],
  },
  {
    id: "evt-004",
    title: "Borsa İstanbul'da BIST 100 günü yüzde 3,2 yükselişle kapattı",
    summary:
      "Küresel risk iştahı ve TCMB sonrası beklentilerle bankacılık öncülüğünde güçlü seans.",
    category: "finance",
    sourceNames: ["Borsa İstanbul", "Bloomberg HT", "KAP"],
    sourceTrustScore: 0.9,
    verificationState: "verified",
    importanceScore: 0.75,
    verificationScore: 0.88,
    locationRelevance: 0.7,
    marketImpactScore: 0.9,
    socialVelocityScore: 0.4,
    noveltyScore: 0.8,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(3),
  },
  {
    id: "evt-005",
    title: "Dışişleri Bakanlığı: bölgedeki ateşkes görüşmeleri yeniden başladı",
    summary:
      "Bakanlık açıklamasında tarafların insani koridor konusunda mutabık kaldığı belirtildi.",
    category: "world",
    sourceNames: ["Dışişleri", "AA", "AFP"],
    sourceTrustScore: 0.92,
    verificationState: "official",
    importanceScore: 0.85,
    verificationScore: 0.95,
    locationRelevance: 0.4,
    marketImpactScore: 0.35,
    socialVelocityScore: 0.5,
    noveltyScore: 0.82,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(4),
    isOfficialSource: true,
  },
  {
    id: "evt-006",
    title: "Meclis'te anayasa değişikliği tasarısı için ilk tur oylaması",
    summary:
      "Tasarı 360 oy eşiğinin altında kaldı; muhalefet ve iktidar grupları arasında sert tartışma yaşandı.",
    category: "politics",
    sourceNames: ["TRT Haber", "Cumhuriyet", "Hürriyet"],
    sourceTrustScore: 0.82,
    verificationState: "corroborated",
    importanceScore: 0.8,
    verificationScore: 0.85,
    locationRelevance: 0.75,
    marketImpactScore: 0.4,
    socialVelocityScore: 0.55,
    noveltyScore: 0.78,
    clickbaitPenalty: 0.05,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(5),
    involvesPublicFigure: true,
  },
  {
    id: "evt-007",
    title: "Ünlü iş insanı hakkında vergi soruşturması iddiası",
    summary:
      "Maliye kaynaklarına dayanan haberlerde şirketler grubuna yönelik inceleme başlatıldığı öne sürülüyor.",
    category: "celebrity",
    sourceNames: ["Ekonomim", "Sözcü"],
    sourceTrustScore: 0.65,
    verificationState: "corroborated",
    importanceScore: 0.55,
    verificationScore: 0.6,
    locationRelevance: 0.5,
    marketImpactScore: 0.45,
    socialVelocityScore: 0.75,
    noveltyScore: 0.7,
    clickbaitPenalty: 0.15,
    tabloidPenalty: 0.2,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(6),
    involvesPublicFigure: true,
  },
  {
    id: "evt-008",
    title: "İstanbul Kadıköy'de iki grup arasında bıçaklı kavga: 2 yaralı",
    summary:
      "Mahalle arasında çıkan tartışmada iki kişi hastaneye kaldırıldı, gözaltılar var.",
    category: "local",
    sourceNames: ["Yerel haber sitesi"],
    sourceTrustScore: 0.35,
    verificationState: "corroborated",
    importanceScore: 0.15,
    verificationScore: 0.4,
    locationRelevance: 0.6,
    marketImpactScore: 0,
    socialVelocityScore: 0.1,
    noveltyScore: 0.6,
    clickbaitPenalty: 0.1,
    tabloidPenalty: 0.3,
    localCrimePenalty: 0.9,
    publishedAt: hoursAgo(2),
    locationLabel: "Kadıköy",
    isLocalViolentCrime: true,
  },
  {
    id: "evt-009",
    title: "Ankara'da motosiklet kazası: sürücü ağır yaralandı",
    summary:
      "E-5 bağlantı yolunda meydana gelen kazada trafik kısa süre aksadı.",
    category: "local",
    sourceNames: ["İHA"],
    sourceTrustScore: 0.4,
    verificationState: "corroborated",
    importanceScore: 0.1,
    verificationScore: 0.35,
    locationRelevance: 0.55,
    marketImpactScore: 0,
    socialVelocityScore: 0.05,
    noveltyScore: 0.5,
    clickbaitPenalty: 0,
    tabloidPenalty: 0.2,
    localCrimePenalty: 0.85,
    publishedAt: hoursAgo(4),
    isLocalViolentCrime: true,
  },
  {
    id: "evt-010",
    title: "Fed faiz kararını yarın açıklayacak — piyasalar temkinli",
    summary:
      "ABD tahvil getirileri yatay seyrederken dolar endeksi hafif yükseldi.",
    category: "finance",
    sourceNames: ["Fed", "Reuters", "Bloomberg"],
    sourceTrustScore: 0.94,
    verificationState: "verified",
    importanceScore: 0.82,
    verificationScore: 0.9,
    locationRelevance: 0.25,
    marketImpactScore: 0.88,
    socialVelocityScore: 0.45,
    noveltyScore: 0.75,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(8),
  },
  {
    id: "evt-011",
    title: "ŞOK! Komşular birbirine girdi — herkes şokta",
    summary:
      "Tıklama tuzağı başlıklı yerel olay haberi, içerikte önemsiz mahalle tartışması.",
    category: "local",
    sourceNames: ["Tıklama haber"],
    sourceTrustScore: 0.2,
    verificationState: "unverified",
    importanceScore: 0.08,
    verificationScore: 0.15,
    locationRelevance: 0.4,
    marketImpactScore: 0,
    socialVelocityScore: 0.2,
    noveltyScore: 0.3,
    clickbaitPenalty: 0.85,
    tabloidPenalty: 0.7,
    localCrimePenalty: 0.75,
    publishedAt: hoursAgo(1),
    isLocalViolentCrime: true,
  },
  {
    id: "evt-012",
    title: "Eski skandal yeniden gündeme düşürüldü — 3 yıl önceki olay",
    summary:
      "Magazin siteleri eski bir ünlü ayrılığını tekrar paylaşıyor, yeni gelişme yok.",
    category: "celebrity",
    sourceNames: ["Magazin portal"],
    sourceTrustScore: 0.25,
    verificationState: "unverified",
    importanceScore: 0.2,
    verificationScore: 0.2,
    locationRelevance: 0.1,
    marketImpactScore: 0,
    socialVelocityScore: 0.15,
    noveltyScore: 0.1,
    clickbaitPenalty: 0.5,
    tabloidPenalty: 0.8,
    localCrimePenalty: 0,
    publishedAt: daysAgo(2),
    involvesPublicFigure: true,
  },
  {
    id: "evt-013",
    title: "KAP: THYAO yıllık bilanço açıklaması yayımlandı",
    summary:
      "Türk Hava Yolları net kârda artış bildirdi; yolcu sayısı rekor seviyede.",
    category: "finance",
    sourceNames: ["KAP", "Investing"],
    sourceTrustScore: 0.96,
    verificationState: "official",
    importanceScore: 0.7,
    verificationScore: 0.97,
    locationRelevance: 0.65,
    marketImpactScore: 0.75,
    socialVelocityScore: 0.3,
    noveltyScore: 0.88,
    clickbaitPenalty: 0,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(6),
    isOfficialSource: true,
  },
  {
    id: "evt-014",
    title: "Orta Doğu'da diplomatik temasların yoğunlaştığına dair erken sinyaller",
    summary:
      "Henüz ana haber ajanslarında teyit yok; sosyal medyada bölge liderleri ve güvenlik konuşuluyor.",
    category: "social_signal",
    sourceNames: ["X erken sinyal", "Bluesky"],
    sourceTrustScore: 0.35,
    verificationState: "unverified",
    importanceScore: 0.65,
    verificationScore: 0.25,
    locationRelevance: 0.35,
    marketImpactScore: 0.4,
    socialVelocityScore: 0.92,
    noveltyScore: 0.95,
    clickbaitPenalty: 0.1,
    tabloidPenalty: 0,
    localCrimePenalty: 0,
    publishedAt: hoursAgo(0.3),
    tags: ["erken sinyal", "orta doğu"],
  },
];

export const SAMPLE_SOCIAL_SIGNALS: SocialSignal[] = [
  {
    id: "sig-001",
    title: "İran / İsrail kelimelerinde 18 dk içinde ani artış",
    summary:
      "X ve Bluesky'de bölgesel gerilim hashtag'leri hızla yayılıyor. GDELT'te henüz sınırlı haber eşleşmesi.",
    keywords: ["iran", "israil", "orta doğu"],
    platforms: [
      { name: "X", postCount: 240 },
      { name: "Bluesky", postCount: 31 },
      { name: "GDELT", postCount: 4 },
    ],
    velocityScore: 0.91,
    status: "tracking",
    relatedEventIds: ["evt-014"],
    detectedAt: hoursAgo(0.3),
    verificationState: "unverified",
  },
  {
    id: "sig-002",
    title: "BTC 98.000$ seviyesi — kripto topluluklarında spike",
    summary:
      "Reddit ve X'te Bitcoin fiyat hedefleri tartışılıyor; resmi piyasa açıklaması yok.",
    keywords: ["bitcoin", "btc", "kripto"],
    platforms: [
      { name: "X", postCount: 520 },
      { name: "Reddit", postCount: 89 },
    ],
    velocityScore: 0.78,
    status: "corroborating",
    relatedEventIds: [],
    detectedAt: hoursAgo(1),
    verificationState: "unverified",
  },
  {
    id: "sig-003",
    title: "YouTube: canlı yayın — büyük şehirde elektrik kesintisi iddiası",
    summary:
      "Yerel gazeteci kanalında kesinti görüntüleri paylaşılıyor, belediye henüz açıklama yapmadı.",
    keywords: ["elektrik", "kesinti", "istanbul"],
    platforms: [{ name: "YouTube", postCount: 12 }],
    velocityScore: 0.55,
    status: "tracking",
    relatedEventIds: [],
    detectedAt: hoursAgo(0.8),
    verificationState: "unverified",
  },
  {
    id: "sig-004",
    title: "Merkez bankası söylentisi — henüz resmi teyit yok",
    summary:
      "Sosyal medyada 'acil faiz' paylaşımları dolaşıyor; TCMB sitesinde yeni duyuru görünmüyor.",
    keywords: ["tcmb", "faiz", "acil"],
    platforms: [
      { name: "X", postCount: 180 },
      { name: "Bluesky", postCount: 22 },
    ],
    velocityScore: 0.65,
    status: "debunked",
    relatedEventIds: ["evt-001"],
    detectedAt: hoursAgo(2),
    verificationState: "corroborated",
  },
];
